imp: better exception reporting
Simple reraising a IllegalParameter from the original ValueError crafts
a correct exception but the result confuses people.

Prior to this change, the following would be output on stderr:

	Traceback (most recent call last):
	  File "/home/julien/Projects/siotls/src/siotls/contents/handshakes/client_hello.py", line 110, in parse_body
	    self = cls(random, cipher_suites, extensions)
	  File "/home/julien/Projects/siotls/src/siotls/contents/handshakes/client_hello.py", line 68, in __init__
	    raise ValueError(e)
	ValueError: cipher suites cannot be empty

	The above exception was the direct cause of the following exception:

	Traceback (most recent call last):
	  File "/home/julien/Projects/siotls/tests/test_contents/test_content_handshakes.py", line 157, in test_content_client_hello_io_reraise_value_error
	    ClientHello.parse_body(stream)
	  File "/home/julien/Projects/siotls/src/siotls/contents/handshakes/client_hello.py", line 112, in parse_body
	    raise alerts.IllegalParameter from exc
	siotls.contents.alerts.IllegalParameter

With this change, it now prints:

	Traceback (most recent call last):
	  File "/home/julien/Projects/siotls/src/siotls/contents/handshakes/client_hello.py", line 110, in parse_body
	    self = cls(random, cipher_suites, extensions)
	  File "/home/julien/Projects/siotls/src/siotls/contents/handshakes/client_hello.py", line 68, in __init__
	    raise ValueError(e)
	ValueError: cipher suites cannot be empty

	The above exception was the direct cause of the following exception:

	Traceback (most recent call last):
	  File "/home/julien/Projects/siotls/tests/test_contents/test_content_handshakes.py", line 157, in test_content_client_hello_io_reraise_value_error
	    ClientHello.parse_body(stream)
	  File "/home/julien/Projects/siotls/src/siotls/contents/handshakes/client_hello.py", line 112, in parse_body
	    raise alerts.IllegalParameter(*exc.args) from exc
	siotls.contents.alerts.IllegalParameter: cipher suites cannot be empty

Only the last line changes, instead of reporting an empty
IllegalParameter, the line now also shows the error message of the
cause.

From a quick survey with a total of 2 (!!!) people, that second
traceback is preferred.